language: python
python:
  - '2.7'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.2
install:
  - pip install -q coverage pep8 pyflakes Django==$DJANGO
before_script:
  - pep8 . --max-line-length=120 --exclude=migrations
  - find . -name '*.py' -not -regex '.*/migrations/.*' -not -regex '.*/__init__.py' -exec pyflakes '{}' \;
  - psql -c 'CREATE DATABASE tour;' -U postgres
script:
  - coverage run --source='tour' --branch --omit='tour/migrations/*' setup.py test
  - coverage report --fail-under=100 --show-missing
